logging:
  level:
    root: INFO
    org:
      springframework: INFO
      apache:
        kafka: INFO
    kafka:
      authorizer:
        logger: INFO
spring:
  main:
    web-application-type: none
    properties:
      spring:
        json:
          use:
            type:
              headers: false
  cache:
    duration: 200
#server:
#  port: 9292